dataset:
  root: Dataset
  batch_size: 32
  num_workers: 4
  val_ratio: 0.1
  test_ratio: 0.1
  include_landmarks: true
  seed: 42
model:
  backbone: resnet18
  use_landmarks: true
  pretrained: true
  dropout: 0.3
trainer:
  epochs: 30
  grad_clip: 1.0
  mixed_precision: true
  loss_weights:
    classification: 1.0
    valence: 0.5
    arousal: 0.5
  save_best_only: true
optimization:
  lr: 0.0003
  weight_decay: 0.0001
scheduler:
  name: cosine
  t_max: 30
  eta_min: 0.000001
